name: Blurt
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-redirect-from
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
paginate: 50
disqus_shortname: vidbina
permalink: /:categories/:title/
url: https://vid.bina.me
plugins:
  - jemoji
