name: Blurt
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-redirect-from
  - jemoji
  - jekyll-gist
  - jekyll-paginate
paginate: 50
emoji_dir: /images/emoji
disqus_shortname: vidbina
permalink: /:categories/:title/
