name: Blurt
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-redirect-from
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
plugins:
  - jemoji
paginate: 50
emoji:
  src: /images/emoji
disqus_shortname: vidbina
permalink: /:categories/:title/
